mysql_root_password: "password"  # Set your root user password here
mysql_databases:
  - name: tooling
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: webaccess
    host: "172.31.32.0/20"  # Replace with actual CIDR or domain
    password: Admin123
    priv: "tooling.*:ALL"
