---
- hosts: all
  name: Include dynamic variables
  become: yes
  tasks:
    - include_tasks: ../dynamic-assignments/env-vars.yml
      tags:
        - always

- hosts: tooling
  import_playbook: ../static-assignments/uat-webservers.yml

- hosts: nginx
  import_playbook: ../static-assignments/loadbalancers.yml

- hosts: database
  import_playbook: ../static-assignments/db-servers.yml


