---
- hosts: all
  become: true
  vars:
    # Define the absolute path to the env-vars directory
    env_vars_dir: "/var/lib/jenkins/workspace/ansible-config-mgt_main/env-vars"

  tasks:
    - include_tasks: ../dynamic-assignments/env-vars.yml
      tags:
        - always

# Import playbooks with specific tags
- import_playbook: ../static-assignments/uat-webservers.yml
  tags:
    - tooling

- import_playbook: ../static-assignments/loadbalancers.yml
  tags:
    - nginx

- import_playbook: ../static-assignments/db-servers.yml
  tags:
    - database




